name: Build and package

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: install rust
              uses: dtolnay/rust-toolchain@master
              with:
                  toolchain: stable

            - name: run tests and linter
              run: cargo test --verbose; cargo clippy

            - name: publish release
              run: cargo publish
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
